#!/bin/sh

name=binutils
version=2.45
revision=1
tarball_url="https://ftpmirror.gnu.org/gnu/binutils/binutils-${version}.tar.xz"
tarball_blake2b="1ce72346b1f531c89feb86b407e2c649151b506ffbd1a02d413411d36f7ede98fa9a1adf75dd941c01df5fe7e6bf151828b269eeb7c278315ca8004bff22eb7f"
hostdeps="libtool pkg-config"
imagedeps="build-essential"

prepare() {
    autotools_recursive_regen -I"$(realpath ./config)"

    cp -pv /usr/local/share/libtool/build-aux/{config.sub,config.guess,install-sh} libiberty/
}