-- Copyright (C) 2024-2025  ilobilo

includes("compiler-rt-builtins/xmake.lua")
includes("cwalk/xmake.lua")
includes("demangler/xmake.lua")
includes("flanterm/xmake.lua")
includes("fmt/xmake.lua")
includes("freestnd-c-hdrs/xmake.lua")
includes("freestnd-cxx-hdrs/xmake.lua")
includes("frigg/xmake.lua")
includes("frozen/xmake.lua")
includes("limine/xmake.lua")
includes("magic_enum/xmake.lua")
includes("ovmf-binaries/xmake.lua")
includes("parallel-hashmap/xmake.lua")
includes("printf/xmake.lua")
includes("smart-ptr/xmake.lua")
includes("string/xmake.lua")
includes("uacpi/xmake.lua")
includes("veque/xmake.lua")