#!/bin/sh

name=mlibc
version=0.0git
revision=1
git_url="https://github.com/managarm/mlibc.git"
commit=1b7f13b45e21ed6ff42e94c026bcefecca9113e5
imagedeps="build-essential meson ninja-build"
hostdeps="gcc pkg-config"
deps="linux-headers mlibc-headers"

early_prepare() {
    meson subprojects download

    curl -Lo libgcc-x86_64.a https://github.com/osdev0/libgcc-binaries/releases/download/2025-08-21/libgcc-x86_64.a
    b2sum libgcc-x86_64.a | grep -q f41054803d2c8475ca394b37e4368aa7ae900bb73409f3d9566b4348797a16efadc97e28ed5db1432c30ba8c4b5ae8fb5ff42ec6d77c2f749765cac89bd66b56
}

configure() {
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS -Wl,${source_dir}/libgcc-${JINX_ARCH}.a" \
    meson_configure_noflags \
        -Dno_headers=true \
        -Dlinux_kernel_headers=${sysroot_dir}${prefix}/include \
        -Ddefault_library=both \
        -Dlibgcc_dependency=false \
        -Duse_freestnd_hdrs=enabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}